name: Sync GHCR Calico images with Docker Hub
on:
  schedule:
    # run every 12h
    - cron:  '0 */12 * * *'
  workflow_dispatch:

jobs:
  mirror-calico:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry (ghcr)
        run: echo ${{ secrets.GHCR_PASSWORD }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Fetch latest Calico release
        id: fetch-latest-release
        run: |
          set -ex

          tigera_image=$(curl -sSL  https://docs.projectcalico.org/manifests/tigera-operator.yaml \
            | awk '/image:/ && NF == 2 { print $2 }')
          tigera_version=${tigera_image##*:}

          versions=$(curl -sSL "https://raw.githubusercontent.com/tigera/operator/${tigera_version}/config/calico_versions.yml" \
            | awk '/version:/ { print $2 }' \
            | sort \
            | uniq)

          echo "Found versions: $versions"

          pushd .github/workflows/
          for version in $versions; do
            ./mirror-calico.sh $version
          done
          popd
